[package]
name = "day07"
version = "0.1.0"
authors = ["J.M. Thiessen <jacob@x0rz3q.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
colored = "2"
itertools = "0.9.0"